### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [tildeio/route-recognizer#139]
Hi @wycats @stefanpenner @rwjblue  ,
We are cdnjs team, we're going to host this library.

[cdnjs](https://cdnjs.com) is one of the most famous free and public web front-end CDN services.

What the files should need to be added in cdnjs?

I know that `route-recognizer.js` and `route-recognizer.js.map` and `route-recognizer.amd.js`@0.1.0 need to be added.
But what about `route-recognizer.cjs.js`@0.1.0 and after v0.2.9's `route-recognizer.es.js` and `route-recognizer.es.js.map` ?
Can these files work on web front-end that CDNJS should host them?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#11497
cdnjs/cdnjs#8444
cdnjs/cdnjs#8410

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

This library is rarely included directly (it's a dependency for other code), so I don't think there is little value in hosting it on a CDN.
