### ISSUE TITLE
Mismatch for nested routes with multiple dynamic segments

### ISSUE THREAD

**Issue by ultimatemonty** [tildeio/route-recognizer#74]
I have a use case where I need to match `/foo/:bar/baz/:bat` while also having `/foo/:bar` in the list of routes. Currently the recognizer will match `/foo/:bar` over `/foo/:bar/baz/:bat`. 

I have a failing test case [here](https://github.com/ultimatemonty/route-recognizer/blob/nested-route-edge-case/tests/recognizer-tests.js#L276-L296).

Happy to PR if someone can point me in the general direction of where to get started.

**Comment by jmeas** [comment]
@ultimatemonty , I think this failing test might be due to a misunderstanding of the API of route-recognizer.

If I've understood your intentions, it looks as if you're trying to use a single call `router.add()` to add multiple "branches" off the "root" route, when this is not possible.

Consider the third example in the README:

```js
router.add([
  { path: "/admin", handler: admin },
  { path: "/posts", handler: posts }
]);
```

Based on my understanding of your interpretation of the API, you might expect this to add two routes:

```
1. {root}/admin
2. {root}/posts
```

In actuality, it is adding:

```
1. {root}/admin
2. {root}/admin/posts
```

Applying this algorithm to your unit tests, we can see that you have registered the following routes:

```
1. {root}/foo/:bar
2. {root}/foo/:bar/baz/:bat
3. {root}/foo/:bar/baz/:bat/foo/:bar/baz/:bat
```

To add multiple "branches" off of the root, you will need to call `router.add()` multiple times, as in [this test.](https://github.com/tildeio/route-recognizer/blob/ed412395a9651c142548865a4f178bbe675b23a1/tests/recognizer-tests.js#L132-L142)

Does that help at all?

**Comment by ultimatemonty** [comment]
@jmeas that makes sense. I was definitely misunderstanding the API. I've moved my test case into it's own test and am still seeing a failure. The specific error I'm getting is:

```
Route Generation: monty test case
    ✘ Died on test #1     at http://localhost:7357/5089/tests/qunit.js:132
        at http://localhost:7357/5089/tests/route-recognizer-test-bundle.js:1126
        at http://localhost:7357/5089/tests/route-recognizer-test-bundle.js:1384: 'undefined' is not an object (evaluating 'results.slice')
```

The updated test can be found [here](https://github.com/ultimatemonty/route-recognizer/commit/410994888ff17bc4d905002d71a9df2771470ec6). I believe I am using the API correctly here.

**Comment by jmeas** [comment]
@ultimatemonty , this test case also seems to be caused by invalid use of the API. The documentation change [in this PR](https://github.com/tildeio/route-recognizer/pull/65) might help you figure it out.

Btw – I wouldn't feel bad about struggling with the API of this library. It's kind of a weird one imo. It definitely took me awhile to figure out how it works :)

**Comment by ultimatemonty** [comment]
@jmeas I updated my test case and it's passing now. So this might not be an issue with this lib. I'm going to close this ticket and work with the ember-cli-mirage team on identifying exactly where the issue is. 

Thanks for all the help - opening issues on GH projects can be super intimidating but you made it a great learning experience!

:+1::+1::+1:

**Comment by jmeas** [comment]
> @jmeas I updated my test case and it's passing now. So this might not be an issue with this lib.

Awesome! Glad to hear that!

> Thanks for all the help

No problem :)

> opening issues on GH projects can be super intimidating but you made it a great learning experience!

Oh yeah, I know how that is. For what it's worth, you were a great issue-opener. Providing the failing test cases made it really easy for me to help ya out. Thanks for that!
